-- Report on Customer Behaviour

--1. Total revenue generated by male vs female customers?

select gender,sum(purchase_amount_usd) from [cleaned_data ]
group by gender 

--2. which customer used the dicount but still spent more than the average amount?
select customer_id, purchase_amount_usd from [cleaned_data ]
where discount_applied='Yes' and purchase_amount_usd >= (select avg(purchase_amount_usd) from [cleaned_data ])

--3 Which are the top 5 products with higher average product review rating?
select distinct top 5 item_purchased, round(avg(review_rating),2) as average_reviews from [cleaned_data ] 
group by item_purchased
order by average_reviews desc

--4 Compare average purchase amount between standard and express shipping
select avg(purchase_amount_usd) ,shipping_type from [cleaned_data ]
where shipping_type in ('Express','Standard')
group by shipping_type

--5. Do subscribed customers spend more? compare the avg spend between the subscribed and non-subscribed customers
select subscription_status, cast(avg(purchase_amount_usd*1.0) as decimal(10,2)) as Purchased_Amount, count(customer_id) as Total_count,sum(purchase_amount_usd) as Total_Spend 
from [cleaned_data ]
group by subscription_status

--6. Which 5 products have highest percentage of purchased products with discount applied?
SELECT TOP 5
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1.0 ELSE 0 END) / COUNT(*) *100,
        2
    ) AS discount_rate
FROM [cleaned_data]
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--7. Segment customers into new , returning and loyal
WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1              THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM [cleaned_data]
)

SELECT customer_segment , count(*)
FROM customer_type
group by customer_segment;

--8. What are the top 3 most purchased products?
WITH ranked_products AS (
    SELECT
        category,
        item_purchased,
        COUNT(*)                                    AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        )                                           AS rnk
    FROM [cleaned_data]
    GROUP BY category, item_purchased
)

SELECT
    category,
    item_purchased,
    total_purchases,
    rnk
FROM ranked_products
WHERE rnk <= 3
ORDER BY category, rnk;

--9. Are customers which are repeat buyers (more than 5 times purchases) likely to be subscribers?
select count(customer_id) , subscription_status from cleaned_data
where previous_purchases > 5
group by subscription_status

--10. What is the revenue collected from each age group
select sum(purchase_amount_usd) ,age_group from [cleaned_data ]
group by age_group
order by age_group